import { profile, projects, experience, skillGroups, coding, education, architecture } from './content.js';

export function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}
const e = escapeHtml;

export function icon(name, className = '') {
  const paths = {
    arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
    external: '<path d="M7 17 17 7M7 7h10v10"/>',
    download: '<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
    moon: '<path d="M20 15a8.5 8.5 0 0 1-11-11A8.5 8.5 0 1 0 20 15Z"/>',
    menu: '<path d="M4 7h16M4 12h16M4 17h16"/>',
    close: '<path d="m6 6 12 12M6 18 18 6"/>',
    copy: '<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>',
    github: '<path d="M8 20v-3c-4 1-4-2-5-3m13 6v-3.5c0-1 .2-1.8-.5-2.5 3-.3 6-1.4 6-6a4.7 4.7 0 0 0-1.3-3.3A4.3 4.3 0 0 0 19 1.5s-1.2-.4-4 1.3a13 13 0 0 0-7 0C5.2 1.1 4 1.5 4 1.5a4.3 4.3 0 0 0-.2 3.7A4.7 4.7 0 0 0 2.5 8.5c0 4.6 3 5.7 6 6-.6.6-.6 1.3-.5 2.5V20"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
    chevron: '<path d="m6 9 6 6 6-6"/>',
  };
  return `<svg class="icon ${e(className)}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.arrow}</svg>`;
}

const tags = items => `<ul class="tags" aria-label="Technologies">${items.map(item => `<li>${e(item)}</li>`).join('')}</ul>`;
const external = (href, label, className = '') => `<a class="${className}" href="${e(href)}" target="_blank" rel="noopener noreferrer">${label}${icon('external')}<span class="sr-only"> (opens in a new tab)</span></a>`;

export function projectVisual(project) {
  if (project.visual === 'intelligence') return `<div class="intelligence-art" aria-hidden="true"><div class="intelligence-window"><div class="intel-bar"><span>Sense.AI</span><i></i><i></i><i></i></div><div class="intel-tabs"><span>For You</span><span>Briefing</span><span>Research</span></div><div class="intel-body"><div class="intel-lead"><span>CONTEXT, CONNECTED</span><p>From signal<br>to <em>perspective.</em></p><b></b><b></b></div><div class="intel-side"><span>SOURCE EVIDENCE</span><b></b><b></b><b></b><hr><span>EDITORIAL REPORT</span><b></b><b></b></div></div></div><span class="intel-caption">COLLECT → UNDERSTAND → CREATE</span></div>`;
  if (project.visual === 'news') return `<div class="news-art" aria-hidden="true">
    <div class="news-input"><span class="art-label">MULTIPLE SOURCES</span>${['Source A', 'Source B', 'Source C'].map((name,i) => `<div class="news-slip"><i class="source-dot source-${i}"></i><span>${name}</span><b></b><b></b></div>`).join('')}</div>
    <div class="news-engine"><div class="engine-orbit"></div><div class="engine-core">OW<span>semantic engine</span></div><span class="engine-line left"></span><span class="engine-line right"></span></div>
    <div class="news-output"><span class="art-label">ONE CLEAR STORY</span><div class="news-result"><div class="result-heading"><i></i><span>Unified story</span></div><b></b><b></b><b></b><div class="result-tags"><span>Clustered</span><span>Summarized</span></div></div></div>
  </div>`;
  if (project.visual === 'notes') return `<div class="notes-art" aria-hidden="true"><div class="note-paper note-back"><span>WORKSPACE / ${e(project.number)}</span><b></b><b></b><b></b></div><div class="note-paper note-front"><span>AN IDEA WORTH KEEPING</span><p>Make room<br>for the next<br><em>good idea.</em></p><svg viewBox="0 0 190 30"><path d="M3 15C45 1 114 3 183 15M6 25c54-12 119-9 175 0"/></svg><i>↗</i></div></div>`;
  return `<div class="digits-art" aria-hidden="true"><div class="digit-grid">7<svg viewBox="0 0 170 170"><path d="M27 38 137 32 69 139M64 84h55"/></svg></div><span class="digit-arrow">→</span><div class="prediction"><span class="art-label">CLASSIFICATION</span><strong>7</strong><span>image → CNN → digit</span></div></div>`;
}

export function caseBody(project) {
  return `<div class="case-body"><p class="case-intro">${e(project.description)}</p><div class="case-block"><span class="eyebrow">THE CHALLENGE</span><p>${e(project.challenge)}</p></div><div class="case-block"><span class="eyebrow">THE APPROACH</span><ol class="case-steps">${project.approach.map((step,i) => `<li><span>${String(i+1).padStart(2,'0')}</span><p>${e(step)}</p></li>`).join('')}</ol></div><div class="case-block"><span class="eyebrow">BUILT WITH</span>${tags(project.stack)}</div><div class="case-takeaway">${icon('arrow')}<p>${e(project.takeaway)}</p></div><div class="case-links">${external(project.source, `${icon('github')} View source`, 'button button-primary')}${project.demo ? external(project.demo, project.demoLabel ? 'Open sample-data demo' : 'Open live site', 'button button-secondary') : ''}</div></div>`;
}

const projectCard = project => `<article class="project-card ${project.featured ? 'project-featured' : ''} project-${e(project.visual)}" data-project-card data-category="${e(project.category)}" data-id="${e(project.id)}">
  <div class="project-visual">${projectVisual(project)}<span class="project-index">${e(project.number)} / SELECTED WORK</span></div>
  <div class="project-info"><div class="project-heading"><div><p class="eyebrow">${e(project.label)}</p><h3>${e(project.name)}</h3><p class="project-subtitle">${e(project.subtitle)}</p></div>${external(project.source, '<span class="sr-only">View '+e(project.name)+' source</span>', 'project-source')}</div><p class="project-description">${e(project.description)}</p>${tags(project.tags)}<button class="project-open js-only" type="button" data-open-project="${e(project.id)}" aria-haspopup="dialog" aria-label="Explore ${e(project.name)} project">Explore project ${icon('arrow')}</button><details class="project-inline"><summary>Explore ${e(project.name)} ${icon('arrow')}</summary>${caseBody(project)}</details>${project.demo ? external(project.demo, e(project.demoLabel || 'Live site'), 'project-demo') : ''}</div>
</article>`;

const experienceItem = (item,i) => `<details class="experience-item" ${item.current ? 'open' : ''}>
  <summary><span class="experience-number">${String(i+1).padStart(2,'0')}</span><span class="experience-heading"><span class="experience-company">${e(item.company)}</span><span class="experience-role">${e(item.roles[0].title)}${item.roles.length>1 ? ' & Software Engineer' : ''}</span></span><span class="experience-meta"><span>${e(item.dates)}</span>${item.current ? '<span class="current-label"><i></i> Current role</span>' : `<span>${e(item.location)}</span>`}</span><span class="experience-expand">${icon('chevron')}</span></summary>
  <div class="experience-content"><p class="experience-summary">${e(item.summary)}</p>${item.roles.map(role => `<section class="role"><div class="role-heading"><h4>${e(role.title)}</h4><span>${e(role.dates)}</span></div>${role.relationship ? `<p class="relationship">${e(role.relationship)} · ${e(item.location)}</p>` : ''}<ul>${role.points.map(point => `<li>${e(point)}</li>`).join('')}</ul></section>`).join('')}${tags(item.tags)}</div>
</details>`;

export function renderHtml({ cssPath = './styles.css', scriptPath = './site.js', year = '2026' } = {}) {
  const structured = { '@context': 'https://schema.org', '@type': 'Person', name: profile.name, url: profile.canonical, jobTitle: 'Lead Engineer — Tizen', sameAs: [profile.github, profile.linkedin, ...coding.map(item => item.url)], knowsAbout: ['Software engineering', 'Tizen', 'Retrieval-augmented generation', 'Backend development', 'On-device AI'] };
  return `<!doctype html>
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Vineet Singh — AI, Systems & Software Engineering</title>
  <meta name="description" content="Vineet Singh builds practical AI tools, reliable backends, and native Tizen experiences. Explore selected projects, engineering experience, and technical skills.">
  <meta name="theme-color" content="#f4f3ee"><meta name="color-scheme" content="light dark">
  <link rel="canonical" href="${profile.canonical}"><link rel="icon" type="image/svg+xml" href="./favicon.svg"><link rel="manifest" href="./site.webmanifest"><link rel="apple-touch-icon" href="./apple-touch-icon.png">
  <meta property="og:type" content="website"><meta property="og:title" content="Vineet Singh — Intelligence, engineered."><meta property="og:description" content="Practical AI. Reliable backends. Native systems. Explore my work and engineering journey."><meta property="og:url" content="${profile.canonical}"><meta property="og:image" content="${profile.canonical}social-card.png">
  <meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Vineet Singh — AI & Systems Engineering"><meta name="twitter:description" content="Practical AI. Reliable backends. Native systems."><meta name="twitter:image" content="${profile.canonical}social-card.png">
  <script>document.documentElement.classList.add('js');try{const t=localStorage.getItem('vineet-portfolio-theme');if(t==='dark'||t==='light')document.documentElement.dataset.theme=t}catch{}</script>
  <link rel="preload" href="./fonts/dm-sans-normal-400-700.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="preload" href="./fonts/instrument-serif-normal-400.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="${cssPath}"><script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script>
  <script type="module" src="${scriptPath}"></script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <div class="scroll-progress" aria-hidden="true"></div>
  <header class="site-header"><div class="header-inner wrap"><a class="brand" href="#home" aria-label="Vineet Singh, home"><span class="brand-mark" aria-hidden="true">v.</span><span>Vineet Singh<span class="brand-discipline">SOFTWARE ENGINEER</span></span></a>
    <nav id="site-nav" class="site-nav" aria-label="Main navigation"><a href="#work">Work</a><a href="#experience">Experience</a><a href="#toolbox">Toolbox</a><a href="#about">About</a><a class="nav-contact" href="#contact">Let’s talk ${icon('external')}</a></nav>
    <div class="header-controls"><button class="icon-button theme-toggle js-only" type="button" aria-label="Switch to dark theme">${icon('moon','theme-moon')}${icon('sun','theme-sun')}</button><button class="icon-button menu-toggle js-only" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="site-nav">${icon('menu','menu-icon')}${icon('close','close-icon')}</button></div>
  </div></header>
  <main id="main" tabindex="-1">
    <section class="hero wrap" id="home" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow hero-eyebrow"><span class="tiny-cross" aria-hidden="true">✳</span> AI · SYSTEMS · FULL STACK</p><h1 id="hero-title">Intelligence,<br><em>engineered.</em></h1><p class="hero-intro">I’m Vineet. I build practical AI tools, reliable backends, and native experiences for Tizen TVs.</p><div class="hero-actions"><a class="button button-primary" href="#work">Explore my work ${icon('arrow')}</a><a class="button button-text" href="${profile.resume}" target="_blank" rel="noopener">View résumé ${icon('external')}<span class="sr-only"> (PDF, opens in a new tab)</span></a></div><div class="current-role"><span class="role-dot" aria-hidden="true"></span><div><strong>Lead Engineer · Tizen</strong><span>Samsung Research Institute Delhi · via Tech Mahindra</span></div></div></div>
      <aside class="architecture-card" aria-label="Explore engineering concepts"><div class="architecture-top"><span class="eyebrow">ENGINEERING IN PRACTICE</span><span class="architecture-marker" aria-hidden="true">[ 01 — 03 ]</span></div><div class="signal-art" aria-hidden="true"><svg viewBox="0 0 480 260"><defs><radialGradient id="signal-glow"><stop offset="0%" stop-color="currentColor" stop-opacity=".14"/><stop offset="100%" stop-color="currentColor" stop-opacity="0"/></radialGradient></defs><ellipse cx="240" cy="128" rx="184" ry="116" fill="url(#signal-glow)"/><g class="signal-lines" fill="none" stroke="currentColor"><ellipse cx="240" cy="128" rx="134" ry="88"/><ellipse cx="240" cy="128" rx="134" ry="88" transform="rotate(60 240 128)"/><ellipse cx="240" cy="128" rx="134" ry="88" transform="rotate(-60 240 128)"/><path d="M40 128h400M240 15v226" stroke-dasharray="2 5"/></g><g class="signal-nodes" fill="currentColor"><circle cx="106" cy="128" r="5"/><circle cx="374" cy="128" r="5"/><circle cx="308" cy="48" r="4"/><circle cx="171" cy="208" r="4"/><circle cx="171" cy="48" r="4"/><circle cx="308" cy="208" r="4"/></g><circle class="signal-center" cx="240" cy="128" r="33"/><text x="240" y="140" text-anchor="middle" class="signal-letter">v.</text></svg><span class="signal-coordinate coordinate-a">INPUT → CONTEXT</span><span class="signal-coordinate coordinate-b">IDEA → IMPLEMENTATION</span></div><div class="architecture-tabs js-only" role="tablist" aria-label="Engineering concepts">${architecture.map((item,i)=>`<button id="tab-${item.id}" type="button" role="tab" aria-controls="architecture-panel" aria-selected="${i===0}" tabindex="${i===0 ? 0 : -1}" data-architecture="${item.id}">${e(item.label)}</button>`).join('')}</div><div id="architecture-panel" class="architecture-panel" role="tabpanel" aria-labelledby="tab-rag" tabindex="0"><p class="architecture-note eyebrow">${e(architecture[0].note)}</p><h2>${e(architecture[0].caption)}</h2><div class="pipeline">${architecture[0].stages.map((stage,i)=>`<span>${e(stage)}</span>${i<3 ? icon('arrow') : ''}`).join('')}</div><p class="architecture-description">${e(architecture[0].description)}</p></div><div class="architecture-bottom"><span class="tiny-cross" aria-hidden="true">+</span><span>INTERACTIVE ARCHITECTURE SKETCH</span></div></aside>
    </section>
    <div class="focus-strip wrap"><span class="strip-label eyebrow">MY FOCUS</span><div><span>01</span> Practical AI</div><div><span>02</span> Native systems</div><div><span>03</span> Dependable backends</div><a href="#experience" aria-label="Explore my engineering experience">${icon('arrow')}</a></div>
    <section class="work-section section wrap" id="work" aria-labelledby="work-title"><div class="section-heading"><div><p class="eyebrow section-number">01 / SELECTED WORK</p><h2 id="work-title">Ideas, made <em>useful.</em></h2></div><p class="section-lead">A few things I’ve built.<br> From local AI pipelines to full stack products.</p></div><div class="work-toolbar"><div class="project-filters js-only" role="group" aria-label="Filter projects"><button class="filter-button" type="button" data-filter="all" aria-pressed="true">All work <span>${String(projects.length).padStart(2,'0')}</span></button><button class="filter-button" type="button" data-filter="ai" aria-pressed="false">AI & ML <span>${String(projects.filter(project => project.category === 'ai').length).padStart(2,'0')}</span></button><button class="filter-button" type="button" data-filter="web" aria-pressed="false">Web apps <span>${String(projects.filter(project => project.category === 'web').length).padStart(2,'0')}</span></button></div><span class="project-count" role="status" aria-live="polite">${projects.length} selected projects</span></div><div class="projects-grid">${projects.map(projectCard).join('')}</div><div class="work-footer"><span>There’s more in the code.</span>${external(profile.github, 'Explore GitHub', 'text-link')}</div></section>
    <section class="experience-section section" id="experience" aria-labelledby="experience-title"><div class="wrap"><div class="section-heading"><div><p class="eyebrow section-number">02 / THE JOURNEY</p><h2 id="experience-title">Built on <em>experience.</em></h2></div><p class="section-lead">From backend foundations<br> to intelligence at the edge.</p></div><div class="experience-list">${experience.map(experienceItem).join('')}</div><div class="experience-footer"><span>For the full picture, see my résumé.</span><a class="text-link" href="${profile.resume}" download>Download CV ${icon('download')}</a></div></div></section>
    <section class="toolbox-section section wrap" id="toolbox" aria-labelledby="toolbox-title"><div class="section-heading"><div><p class="eyebrow section-number">03 / THE TOOLBOX</p><h2 id="toolbox-title">Different tools.<br><em>One engineering mindset.</em></h2></div><p class="section-lead">Choose the right abstraction.<br> Understand what’s underneath.</p></div><div class="skills-grid">${skillGroups.map(group=>`<article class="skill-group"><span class="skill-number">${group.number} /</span><h3>${e(group.title)}</h3><p>${e(group.text)}</p>${tags(group.skills)}</article>`).join('')}</div></section>
    <section class="about-section section" id="about" aria-labelledby="about-title"><div class="about-grid wrap"><div class="about-copy"><p class="eyebrow section-number">04 / A LITTLE CONTEXT</p><h2 id="about-title">Curiosity, with<br><em>a practical streak.</em></h2><p>My work sits between application development, AI, and the systems those applications run on. I enjoy connecting the pieces—from a useful interface to the backend, model, and native platform behind it.</p><p>Today, that means Tizen TV integrations, local AI tools, and exploring what inference can do within a small memory budget.</p><div class="education-card"><span class="eyebrow">THE FOUNDATION</span><h3>${e(education.degree)}</h3><p>${e(education.school)}</p><div><span>${e(education.dates)}</span><span>${e(education.location)}</span></div></div></div><div class="coding-card"><div class="coding-header"><span class="eyebrow">KEEP SOLVING</span><span aria-hidden="true">{ }</span></div><h3>Thinking in<br><em>problems & patterns.</em></h3><p>Find my coding practice and contest profiles here.</p><div class="coding-links">${coding.map(item=>external(item.url, `<span><strong>${e(item.name)}</strong><small>@${e(item.username)}</small></span><span class="coding-rating">${e(item.rating)}<small>Résumé rating</small></span>`, 'coding-link')).join('')}</div><span class="coding-footnote">Ratings as listed in my résumé · ${e(profile.updated)}</span></div></div></section>
    <section class="contact-section" id="contact" aria-labelledby="contact-title"><div class="contact-inner wrap"><div class="contact-top"><p class="eyebrow section-number">05 / LET’S CONNECT</p><span class="contact-location">${icon('sun')} ${e(profile.location)}</span></div><h2 id="contact-title">Have something<br><em>in mind?</em></h2><div class="contact-bottom"><p>Let’s talk about AI, systems,<br>or the next useful thing to build.</p><div class="email-group"><a class="email-link" href="mailto:${profile.email}">${profile.email}${icon('external')}</a><button class="copy-email js-only" type="button" aria-label="Copy email address">${icon('copy')}</button><span class="copy-status sr-only" role="status" aria-live="polite"></span></div></div><div class="contact-links">${external(profile.linkedin, 'LinkedIn', 'text-link')}${external(profile.github, 'GitHub', 'text-link')}<a class="text-link" href="tel:${profile.phone.replace(/\s/g, '')}" aria-label="Call Vineet Singh at ${e(profile.phone)}">Phone ${icon('external')}</a><a class="text-link" href="${profile.resume}" target="_blank" rel="noopener">Résumé ${icon('external')}<span class="sr-only"> (PDF, opens in a new tab)</span></a></div></div></section>
  </main>
  <footer class="site-footer"><div class="wrap footer-inner"><a class="brand footer-brand" href="#home"><span class="brand-mark" aria-hidden="true">v.</span><span>Vineet Singh</span></a><span>Thoughtfully built. Always evolving.</span><span>© ${e(year)} Vineet Singh</span><a class="back-to-top" href="#home">Back to top ${icon('arrow')}</a></div></footer>
  <dialog class="case-dialog" aria-labelledby="dialog-title"><div class="dialog-shell"><header class="dialog-header"><span class="eyebrow dialog-label">PROJECT / 01</span><button class="icon-button dialog-close" type="button" aria-label="Close project details">${icon('close')}</button></header><div class="dialog-title-block"><span class="eyebrow dialog-category"></span><h2 id="dialog-title" aria-live="polite"></h2><p class="dialog-subtitle"></p></div><div class="dialog-body"></div><footer class="dialog-footer"><button class="text-link previous-project" type="button">${icon('arrow')} Previous project</button><span class="dialog-position"></span><button class="text-link next-project" type="button">Next project ${icon('arrow')}</button></footer></div></dialog>
</body></html>`;
}
